// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: newrpc.proto

package newrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Newrpc_Ping_FullMethodName = "/newrpc.Newrpc/Ping"
)

// NewrpcClient is the client API for Newrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewrpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type newrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNewrpcClient(cc grpc.ClientConnInterface) NewrpcClient {
	return &newrpcClient{cc}
}

func (c *newrpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Newrpc_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewrpcServer is the server API for Newrpc service.
// All implementations must embed UnimplementedNewrpcServer
// for forward compatibility.
type NewrpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedNewrpcServer()
}

// UnimplementedNewrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewrpcServer struct{}

func (UnimplementedNewrpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNewrpcServer) mustEmbedUnimplementedNewrpcServer() {}
func (UnimplementedNewrpcServer) testEmbeddedByValue()                {}

// UnsafeNewrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewrpcServer will
// result in compilation errors.
type UnsafeNewrpcServer interface {
	mustEmbedUnimplementedNewrpcServer()
}

func RegisterNewrpcServer(s grpc.ServiceRegistrar, srv NewrpcServer) {
	// If the following call pancis, it indicates UnimplementedNewrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Newrpc_ServiceDesc, srv)
}

func _Newrpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Newrpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewrpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Newrpc_ServiceDesc is the grpc.ServiceDesc for Newrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Newrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newrpc.Newrpc",
	HandlerType: (*NewrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Newrpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "newrpc.proto",
}
