// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: newrpc.proto

package server

import (
	"context"

	"gozero/newrpc/internal/logic"
	"gozero/newrpc/internal/svc"
	"gozero/newrpc/newrpc"
)

type NewrpcServer struct {
	svcCtx *svc.ServiceContext
	newrpc.UnimplementedNewrpcServer
}

func NewNewrpcServer(svcCtx *svc.ServiceContext) *NewrpcServer {
	return &NewrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *NewrpcServer) Ping(ctx context.Context, in *newrpc.Request) (*newrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
