// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: gouser.proto

package server

import (
	"context"

	"gozero/gouser/internal/logic"
	"gozero/gouser/internal/svc"
	"gozero/gouser/types/gouser"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	gouser.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) UserInfo(ctx context.Context, in *gouser.UserInfoRequest) (*gouser.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UsersServer) UserCreate(ctx context.Context, in *gouser.UserCreateRequest) (*gouser.UserCreateResponse, error) {
	l := logic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
