// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: newrpc.proto

package newrpcclient

import (
	"context"

	"gozero/newrpc/newrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = newrpc.Request
	Response = newrpc.Response

	Newrpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultNewrpc struct {
		cli zrpc.Client
	}
)

func NewNewrpc(cli zrpc.Client) Newrpc {
	return &defaultNewrpc{
		cli: cli,
	}
}

func (m *defaultNewrpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := newrpc.NewNewrpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
